In [2]:
#list
list1 = list(range(12))
print(list1)
list1[8]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


8

In [7]:
#ndArray
import numpy as np
ndArray12_ = np.array(list1)
print(ndArray12_)
print(ndArray12_.shape)
ndArray12_[8,]

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


8

In [10]:
#ndArray
ndArray2_6 = ndArray12_.reshape((2,6))
print(ndArray2_6)
print(ndArray2_6.shape)
ndArray2_6[1,2]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


8

In [11]:
#ndArray
ndArray4_3 = ndArray12_.reshape((4,3))
print(ndArray4_3.shape)
ndArray4_3[2,2]

(4, 3)


8

In [12]:
#ndArray
ndArray2_3_2 = ndArray12_.reshape((2, 3, 2))
print(ndArray2_3_2.shape)
ndArray2_3_2[1,1,0]


(2, 3, 2)


8

In [21]:
# mean(),sum(),std()
#10個同學,每個同學5個分數
import numpy as np
arr=np.random.randint(50,101,size=(10,5))
print(arr.shape)
arr

(10, 5)


array([[96, 68, 64, 68, 85],
       [83, 74, 64, 95, 54],
       [55, 64, 53, 51, 51],
       [84, 83, 62, 56, 95],
       [81, 79, 70, 89, 76],
       [67, 87, 83, 93, 81],
       [78, 93, 59, 68, 93],
       [58, 85, 76, 59, 68],
       [82, 70, 85, 92, 66],
       [86, 98, 86, 54, 68]])

In [22]:
#加總sum()
arr.sum()

3735

In [23]:
#平均mean()
arr.mean()

74.7

In [24]:
#標準差
arr.std()

13.698540068197048

In [25]:
#每個學生的總分
arr.sum(axis=1)

array([381, 370, 274, 380, 395, 411, 391, 346, 395, 392])

In [26]:
#np.sum()
np.sum(arr, axis=1)

array([381, 370, 274, 380, 395, 411, 391, 346, 395, 392])

In [30]:
#每個學生的總分
studentAVG = arr.mean(axis=1)

In [31]:
#全班最高平均
studentAVG.max()

82.2

In [32]:
#全班最高低均
studentAVG.min()

54.8