In [13]:
#建立50位學生的中文和英文的分數
import random
chinese = [random.randint(60,100) for _ in range(50)]
english = [random.randint(60,100) for _ in range(50)]
print('chinese', chinese)
print('english', english)

chinese [61, 79, 73, 82, 89, 75, 95, 88, 76, 75, 91, 79, 61, 61, 81, 67, 60, 88, 70, 85, 88, 99, 70, 96, 74, 78, 90, 97, 95, 61, 60, 73, 99, 88, 97, 92, 70, 81, 84, 78, 77, 61, 95, 64, 60, 74, 87, 81, 84, 86]
english [77, 91, 82, 61, 69, 93, 87, 94, 67, 82, 93, 88, 68, 95, 90, 67, 65, 83, 98, 97, 85, 70, 84, 90, 87, 95, 92, 82, 73, 79, 86, 83, 86, 82, 89, 82, 88, 92, 63, 96, 67, 92, 82, 93, 73, 79, 75, 71, 66, 86]


In [ ]:
#中文和英文的總合
result = []
for i in range(50):
    total = chinese[i] + english[i]
    result.append(total)
result

#使用comprehension來建立中文和英文的總合
result = [chinese[i]+english[i] for i in range(50)]
result


In [11]:
#numpy可以陣列和陣列做運算
import numpy as np
ndChinese=np.array(chinese)
print(ndChinese.__class__)
ndEnglish=np.array(english)
print(ndEnglish)
ndChinese + ndEnglish

<class 'numpy.ndarray'>
[91 61 70 63 78 86 98 95 63 82 69 79 70 83 80 89 76 63 85 98 76 99 77 72
 80 97 81 74 97 68 71 76 93 76 82 79 98 72 77 63 72 92 72 98 83 93 80 87
 83 79]


array([175, 133, 149, 160, 176, 182, 165, 193, 140, 156, 158, 167, 136,
       158, 180, 171, 144, 130, 158, 195, 154, 169, 177, 145, 150, 186,
       165, 168, 159, 143, 147, 151, 192, 154, 143, 156, 198, 161, 176,
       140, 144, 172, 150, 177, 167, 180, 161, 149, 159, 170])

In [20]:
import numpy as np
l =[[1,2,3],[4, 5, 6]]
a=np.array(l) #建立ndarray
#使用ndarray的屬性 ndim,shape,size,dtype
print(a.__class__)
print('維度:',a.ndim)
print('形狀:',a.shape)
print('size:',a.size)
print('資料類型:',a.dtype)

<class 'numpy.ndarray'>
維度: 2
形狀: (2, 3)
size: 6
資料類型: int64


In [30]:
#產生亂數陣列
import numpy as np

np.random.seed(6785)
data = np.random.rand(2,3)
data * 10

array([[7.44294269, 2.78022403, 8.59989025],
       [0.92609429, 6.95958674, 1.54796121]])

In [32]:
data += data
data

array([[2.97717708, 1.11208961, 3.4399561 ],
       [0.37043771, 2.7838347 , 0.61918449]])