In [2]:
#list
list1 = list(range(12))
print(list1)
list1[8]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


8

In [7]:
#ndArray
import numpy as np
ndArray12_ = np.array(list1)
print(ndArray12_)
print(ndArray12_.shape)
ndArray12_[8,]

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


8

In [10]:
#ndArray
ndArray2_6 = ndArray12_.reshape((2,6))
print(ndArray2_6)
print(ndArray2_6.shape)
ndArray2_6[1,2]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


8

In [11]:
#ndArray
ndArray4_3 = ndArray12_.reshape((4,3))
print(ndArray4_3.shape)
ndArray4_3[2,2]

(4, 3)


8

In [12]:
#ndArray
ndArray2_3_2 = ndArray12_.reshape((2, 3, 2))
print(ndArray2_3_2.shape)
ndArray2_3_2[1,1,0]


(2, 3, 2)


8