In [1]:
#list
#建立50位學生的中文和英文的分數

import random
chinese = [random.randint(60, 100) for _ in range(50)]#comprehension
english = [random.randint(60, 100) for _ in range(50)]
print(chinese)
print(english)

[80, 76, 72, 99, 93, 98, 60, 85, 80, 71, 63, 73, 96, 98, 100, 82, 97, 70, 67, 92, 68, 95, 86, 70, 80, 90, 92, 68, 67, 90, 62, 79, 94, 68, 78, 78, 80, 67, 71, 60, 70, 79, 70, 97, 73, 66, 76, 79, 88, 64]
[87, 84, 77, 63, 70, 75, 73, 77, 92, 93, 63, 61, 90, 67, 78, 86, 94, 64, 67, 87, 75, 61, 76, 69, 80, 68, 63, 78, 99, 69, 61, 78, 99, 61, 61, 71, 76, 64, 98, 66, 63, 80, 99, 84, 73, 95, 71, 88, 82, 74]


In [ ]:
#2個list的加總
result = []
for i in range(50):
    total = chinese[i] + english[i]
    result.append(total)
result

In [5]:
#ndArray
#建立50位學生的中文和英文的分數
import numpy as np
ndChinese = np.array(chinese)
ndEnglish = np.array(english)
print(ndChinese)
print(ndEnglish)
ndResult = ndChinese + ndEnglish
ndResult

[ 80  76  72  99  93  98  60  85  80  71  63  73  96  98 100  82  97  70
  67  92  68  95  86  70  80  90  92  68  67  90  62  79  94  68  78  78
  80  67  71  60  70  79  70  97  73  66  76  79  88  64]
[87 84 77 63 70 75 73 77 92 93 63 61 90 67 78 86 94 64 67 87 75 61 76 69
 80 68 63 78 99 69 61 78 99 61 61 71 76 64 98 66 63 80 99 84 73 95 71 88
 82 74]


array([167, 160, 149, 162, 163, 173, 133, 162, 172, 164, 126, 134, 186,
       165, 178, 168, 191, 134, 134, 179, 143, 156, 162, 139, 160, 158,
       155, 146, 166, 159, 123, 157, 193, 129, 139, 149, 156, 131, 169,
       126, 133, 159, 169, 181, 146, 161, 147, 167, 170, 138])

In [8]:
#將2維list轉換為ndArray

ls_2d = [[1,2,3],
      [2,3,4]
     ]
nd_2d = np.array(ls_2d)
nd_2d

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
nd_2d.ndim

2

In [11]:
nd_2d.size

6

In [12]:
nd_2d.shape

(2, 3)

In [13]:
nd_2d.dtype

dtype('int64')

In [15]:
#使用numpy的random
data = np.random.rand(2, 3)
data

array([[0.77175323, 0.87284   , 0.76691612],
       [0.81131648, 0.9278035 , 0.18888982]])

In [16]:
data * 10

array([[7.7175323 , 8.72840001, 7.66916121],
       [8.11316479, 9.27803498, 1.88889824]])

In [17]:
np.random.randint(2, size=10)

array([0, 1, 0, 1, 0, 0, 1, 1, 1, 0])

In [19]:
np.random.randint(5, size=(2,4))

array([[2, 4, 2, 4],
       [4, 0, 2, 0]])

In [20]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10])
a

array([-1.7,  1.5, -0.2,  0.6, 10. ])

In [21]:
np.floor(a)

array([-2.,  1., -1.,  0., 10.])

In [22]:
np.ceil(a)

array([-1.,  2., -0.,  1., 10.])

In [24]:
nd_a = np.arange(12)
nd_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
nd_a.shape

(12,)

In [28]:
nd_b = nd_a.reshape((3,4))
nd_b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
nd_b.shape

(3, 4)

In [31]:
nd_c = nd_b.reshape((4,3))
nd_c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
nd_c.shape

(4, 3)

In [33]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [37]:
import numpy as np
arr = np.random.randint(50,101,size=(10,5)) #10個學生 5個分數


array([[ 98,  63,  51,  54,  95],
       [ 64,  56,  68,  71,  76],
       [ 51,  91,  75,  84,  58],
       [ 91,  50,  87,  84,  58],
       [ 73,  59,  64,  86,  67],
       [ 69, 100,  93,  60,  78],
       [ 80,  84,  72,  61,  96],
       [ 56,  67,  83,  79,  74],
       [ 95,  71,  52,  88,  98],
       [ 93,  63,  96,  89,  90]])

In [38]:
#統計功能mean,sum(),std(),max(),min()
arr.sum()

3761

In [41]:
np.sum(arr[:3])

1055

In [46]:
#每個學生的總分
sum_students = arr.sum(axis=1)
sum_students

array([361, 335, 359, 370, 349, 400, 393, 359, 404, 431])

In [47]:
mean_students = arr.mean(axis=1)
mean_students

array([72.2, 67. , 71.8, 74. , 69.8, 80. , 78.6, 71.8, 80.8, 86.2])

In [49]:
#學生最高總分是
sum_students.max()

431

In [51]:
#學生最高平均是
mean_students.max()

86.2

In [53]:
incomeOfWeek = np.array([456, 896, 278, 832, 940, 1265, 689])
#累計每日的收入 cumsum
incomeOfWeek.cumsum()


array([ 456, 1352, 1630, 2462, 3402, 4667, 5356])