In [ ]:
import json
#json_file = open('新北市公共自行車租賃系統.json','w',encoding='utf-8')
#json_file.close()

#使用with as ,離開程式區塊時,會自動關閉檔案物件

with open('新北市公共自行車租賃系統.json','r',encoding='utf-8') as json_file:
    jsonData = json.load(json_file)
    #jsonData是python Dictionary
    if jsonData['success']:
        records = jsonData['result']['records']
    else:
        print("資料沒有完整")

for station in records:
    if '汐止區' in station['sarea']:
        print('區域',station['sarea'])
        print('站名',station['sna'])
        print('地址',station['ar'])
        print('緯經度座標[{},{}]'.format(station['lat'],station['lng']))
        print('全部數量',station['tot'])
        print('可借',station['sbi'])
        print('可還',station['bemp'])
        print('------------------------')
        print()

        

In [17]:
import numpy as np
#要建立2維ndarray
l = [[1, 2, 3],
     [2, 3, 4]]
a = np.array(l)
a

a.ndim

2

In [18]:
a.shape

(2, 3)

In [19]:
a.size

6

In [20]:
a.dtype

dtype('int64')

In [21]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[-1.33445178, -2.1227272 , -1.97064279],
       [-0.80238611,  1.33904972, -0.03161962]])

In [22]:
data * 10

array([[-13.34451781, -21.22727204, -19.7064279 ],
       [ -8.02386107,  13.39049719,  -0.31619618]])

In [23]:
data += data
data

array([[-2.66890356, -4.24545441, -3.94128558],
       [-1.60477221,  2.67809944, -0.06323924]])