In [1]:
import numpy as np
data = np.random.randn(2,3)
data

array([[-0.70454855, -1.14317398,  2.15560869],
       [-0.15881634,  0.1997899 , -0.74644848]])

In [2]:
data * 10

array([[ -7.04548552, -11.43173982,  21.55608688],
       [ -1.58816338,   1.99789902,  -7.46448477]])

In [3]:
data.ndim


2

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

In [6]:
data.size

6

In [7]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.shape

(2, 4)

In [9]:
arr2.dtype

dtype('int64')

In [14]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.empty((2, 3, 2))

array([[[1.04e-322, 0.00e+000],
        [0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000]],

       [[0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000]]])

In [22]:
arr1 = np.array([1, 2, 3], dtype=np.float128)
arr1
arr1.dtype

dtype('float128')

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [26]:
#ndarray轉型方法->astype(np.float64)
newArray = arr.astype(np.float128)
newArray.dtype

dtype('float128')

### 比較

In [28]:
import numpy as np
arr = np.array([[1., 2. ,3.],[4., 5., 6.]])
arr < 5

array([[ True,  True,  True],
       [ True, False, False]])

In [30]:
arr2 = np.array([[0., 4., 1.],[7., 2. ,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [31]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])