In [1]:
#數學運算和資料對齊
import numpy as np
import pandas as pd

s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [2]:
s1 * 2

a    14.6
c    -5.0
d     6.8
e     3.0
dtype: float64

In [3]:
# series 和 series運算
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [4]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [5]:
#運算時使用索引標籤對齊
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [8]:

#dataFrame數學運算時同時對齊row和columns標籤
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),
                  columns=list('bcd'),
                  index=['台北','台中','台南'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                  columns = list('bde'),
                  index=['高雄','台北','台中','台南'])
df1

b    c    d
台北  0.0  1.0  2.0
台中  3.0  4.0  5.0
台南  6.0  7.0  8.0

In [9]:
df2

b     d     e
高雄  0.0   1.0   2.0
台北  3.0   4.0   5.0
台中  6.0   7.0   8.0
台南  9.0  10.0  11.0

In [10]:
df1 + df2

b   c     d   e
台中   9.0 NaN  12.0 NaN
台北   3.0 NaN   6.0 NaN
台南  15.0 NaN  18.0 NaN
高雄   NaN NaN   NaN NaN

In [11]:
#相同row,不同的column標籤對齊
df1 = pd.DataFrame({'A':[1, 2]})
df2 = pd.DataFrame({'B':[3, 4]})
df1

A
0  1
1  2

In [12]:
df2

B
0  3
1  4

In [13]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [14]:
#數學運算實體方法
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [15]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [16]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [18]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [19]:
#DataFrame 和 Series
arr = np.arange(12.).reshape((4, 3))
arr

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [20]:
arr[0]

array([0., 1., 2.])

In [21]:
arr - arr[0]

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.],
       [9., 9., 9.]])

In [22]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['高雄','台北','台中','台南'])
frame

b     d     e
高雄  0.0   1.0   2.0
台北  3.0   4.0   5.0
台中  6.0   7.0   8.0
台南  9.0  10.0  11.0

In [23]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: 高雄, dtype: float64

In [24]:
frame - series

b    d    e
高雄  0.0  0.0  0.0
台北  3.0  3.0  3.0
台中  6.0  6.0  6.0
台南  9.0  9.0  9.0

In [25]:
#Function 和 Mapping
frame = pd.DataFrame(np.random.randn(4,3),
                    columns=list('bde'),
                    index=['台北','台中','台南','高雄'])
frame

b         d         e
台北 -0.711971 -0.254095 -0.886533
台中  1.848631  0.484798 -0.455876
台南 -1.491483 -1.663443 -0.604214
高雄  0.355930  0.105625  1.578592

In [27]:
#numpy有提供一些數學function
np.abs(frame)

b         d         e
台北  0.711971  0.254095  0.886533
台中  1.848631  0.484798  0.455876
台南  1.491483  1.663443  0.604214
高雄  0.355930  0.105625  1.578592

In [28]:
#dataFrame實體方法apply(function)
frame

b         d         e
台北 -0.711971 -0.254095 -0.886533
台中  1.848631  0.484798 -0.455876
台南 -1.491483 -1.663443 -0.604214
高雄  0.355930  0.105625  1.578592

In [29]:
def max_min(x):
    return x.max() - x.min()

frame.apply(max_min)

b    3.340114
d    2.148241
e    2.465125
dtype: float64

In [30]:
frame.apply(lambda x: x.max() - x.min())

b    3.340114
d    2.148241
e    2.465125
dtype: float64

In [31]:
frame.apply(lambda x:x.max() - x.min(),axis=1)

台北    0.632438
台中    2.304507
台南    1.059229
高雄    1.472967
dtype: float64