In [18]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a.shape

(2, 3)

In [20]:
b = np.resize(a, (3,2)) 
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
b.shape


(3, 2)

In [22]:
a[0,1]=100

In [23]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])