In [4]:
import numpy as np
nd1 = np.arange(12)
print(nd1)
print(nd1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [2]:
nd1[8,]

8

In [5]:
#reshape成為2維
nd2 = nd1.reshape((2,6))
nd2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [6]:
#reshape成為2維
nd3 = nd1.reshape((3, 4))
nd3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
nd3[2,]

array([ 8,  9, 10, 11])

In [9]:
nd3[2,2]

10

In [11]:
nd3[2,2:]

array([10, 11])

In [12]:
nd4 = nd1.reshape((2,3,2))
nd4

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [15]:
#numpy的統計
#sum()
#10個學生,5個分數
students = np.random.randint(60,100,size=(10,5))
students

array([[63, 68, 83, 61, 87],
       [65, 75, 72, 86, 69],
       [89, 88, 86, 63, 93],
       [82, 90, 66, 97, 63],
       [89, 96, 80, 82, 78],
       [74, 67, 99, 64, 91],
       [70, 93, 75, 77, 70],
       [89, 76, 80, 78, 91],
       [80, 87, 82, 63, 71],
       [90, 82, 68, 65, 75]])

In [18]:
#學生總分
students.sum(axis=1)

array([362, 367, 419, 398, 425, 395, 385, 414, 383, 380])

In [20]:
#學生平均
students.mean(axis=1)

array([72.4, 73.4, 83.8, 79.6, 85. , 79. , 77. , 82.8, 76.6, 76. ])

In [21]:
#各科的標準差,數值愈大代表分數差距比較大
students.std(axis=0)

array([ 9.94434513,  9.73447482,  9.11537163, 11.62927341, 10.32279032])

In [22]:
#各科最高分
students.max(axis=0)

array([90, 96, 99, 97, 93])

In [23]:
#各科最底分
students.min(axis=0)

array([63, 67, 66, 61, 63])

In [24]:
#1家分店30天的營收

oneStore = np.random.randint(100,10000,size=(30,))
oneStore

array([5552, 6241, 9895, 1611,  726, 5606, 1296, 4533, 8268, 6787,  167,
       5287, 9743,  820, 1273, 9259, 6807, 7855, 2138, 6351, 8975, 2828,
       5064, 4807, 2643, 6529, 7889,  830, 3681,  616])

In [27]:
#累計每天這家店的營收
#cumsum()
oneStoreCum = oneStore.cumsum()
oneStoreCum

array([  5552,  11793,  21688,  23299,  24025,  29631,  30927,  35460,
        43728,  50515,  50682,  55969,  65712,  66532,  67805,  77064,
        83871,  91726,  93864, 100215, 109190, 112018, 117082, 121889,
       124532, 131061, 138950, 139780, 143461, 144077])