In [5]:
#由list建立numpy
#np.array()


import numpy as np
import random

chinese = [random.randint(60,100) for _ in range(50)]
english = [random.randint(60,100) for _ in range(50)]

ndChinese = np.array(chinese)
ndEnglish = np.array(english)


array([ 72,  60,  80,  79,  64,  91,  67,  73,  75,  96,  66,  85,  93,
        67,  88,  61,  96,  98,  91,  83, 100,  79,  84,  60,  72,  93,
        94,  86,  96,  67,  98,  63,  86,  84,  92,  82,  68,  82,  64,
        76,  68,  81,  97,  93,  85,  98,  66,  84,  81,  76])

In [8]:
#每個學生的總分
ndTotal = ndChinese + ndEnglish
ndTotal

array([169, 141, 165, 149, 156, 162, 143, 133, 164, 182, 149, 185, 173,
       167, 166, 132, 168, 169, 169, 152, 194, 143, 157, 146, 134, 174,
       161, 170, 182, 162, 197, 142, 182, 160, 156, 175, 134, 154, 149,
       174, 153, 169, 173, 191, 168, 164, 138, 157, 174, 175])

In [9]:
#每個學生的平均
#一維陣列
ndAverage = ndTotal / 2
ndAverage

array([84.5, 70.5, 82.5, 74.5, 78. , 81. , 71.5, 66.5, 82. , 91. , 74.5,
       92.5, 86.5, 83.5, 83. , 66. , 84. , 84.5, 84.5, 76. , 97. , 71.5,
       78.5, 73. , 67. , 87. , 80.5, 85. , 91. , 81. , 98.5, 71. , 91. ,
       80. , 78. , 87.5, 67. , 77. , 74.5, 87. , 76.5, 84.5, 86.5, 95.5,
       84. , 82. , 69. , 78.5, 87. , 87.5])

In [10]:
ndAverage.__class__

numpy.ndarray

In [11]:
ndAverage.ndim

1

In [12]:
ndAverage.shape

(50,)

In [13]:
ndAverage.size

50

In [14]:
ndAverage.dtype

dtype('float64')

In [15]:
#建立2維的ndArray
l1 = [
    [1, 2, 3],
    [2, 3, 4]
]
a = np.array(l1)
a

array([[1, 2, 3],
       [2, 3, 4]])

In [16]:
a.ndim

2

In [17]:
a.shape

(2, 3)

In [18]:
a.size

6

In [19]:
a.dtype

dtype('int64')