In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 15.7 ms, sys: 5.76 ms, total: 21.4 ms
Wall time: 20.2 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 672 ms, sys: 228 ms, total: 899 ms
Wall time: 922 ms


In [8]:
#list轉為ndarray
a = np.array([1, 3, 5, 7, 9])
b = np.array([3, 5, 6, 7, 9])
c = a + b
print(c)

print(type(c))

[ 4  8 11 14 18]
<class 'numpy.ndarray'>


In [7]:
[1, 3, 5, 7, 9] + [3, 5, 6, 7, 9]

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [16]:
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)

[ 4  8 11 14 18]
1
(5,)
5
int64


In [18]:
ml = [[1,2,3],[4,5,6]]
ml[0][2]

3

In [19]:
ndml = np.array(ml)
print(ndml)
print(ndml.ndim)
print(ndml.shape)
print(ndml.size)
print(ndml.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [21]:
import random
random.randint(1,10)

6

In [35]:
import numpy as np
data = np.random.randn(50,5)
print(data)
print(data * 10 + 50)
print(data.ndim)
print(data.shape)
print(data.dtype)

data = data * 10 + 50

newData = data.astype(np.int64)
newData

[[ 8.93390393e-01 -1.60415733e+00  3.28236911e-01  6.30430871e-02
   1.48510750e+00]
 [ 7.83985124e-01  6.60091637e-01 -1.84508439e-01 -4.18899493e-01
   5.45105724e-01]
 [ 1.92263852e+00 -7.41853870e-01  4.78162092e-02 -2.53923843e-01
  -1.91720689e-01]
 [ 1.10787358e+00 -7.40675829e-01 -4.39884833e-01 -7.47547996e-01
   1.93373431e+00]
 [-6.63053814e-01 -6.88929302e-01  2.47052189e-01  2.89186325e+00
  -2.26002221e+00]
 [-5.96870693e-01 -1.38878324e+00  4.35066214e-01 -1.46847979e+00
  -2.21407330e+00]
 [ 7.07252116e-01  5.25069963e-01 -1.47656070e+00  7.27551294e-01
   7.20605046e-01]
 [ 1.32074690e+00  1.64444712e+00  1.10654782e+00 -1.50005681e+00
   8.75849837e-01]
 [ 7.96383531e-01 -4.71073591e-01 -3.41697180e-01  2.85733243e-01
  -5.47646802e-01]
 [-1.84447287e+00 -4.08040870e-01  9.51917228e-01  6.99475472e-01
  -5.52216608e-01]
 [-7.39081130e-01 -8.71736691e-02  8.26778801e-01 -9.13697272e-01
  -2.23320504e+00]
 [-1.10373324e+00  9.92579459e-01  1.27641275e+00  8.67296123e-01

array([[58, 33, 53, 50, 64],
       [57, 56, 48, 45, 55],
       [69, 42, 50, 47, 48],
       [61, 42, 45, 42, 69],
       [43, 43, 52, 78, 27],
       [44, 36, 54, 35, 27],
       [57, 55, 35, 57, 57],
       [63, 66, 61, 34, 58],
       [57, 45, 46, 52, 44],
       [31, 45, 59, 56, 44],
       [42, 49, 58, 40, 27],
       [38, 59, 62, 58, 56],
       [38, 49, 56, 61, 51],
       [56, 41, 59, 53, 29],
       [63, 50, 55, 52, 57],
       [39, 50, 47, 52, 48],
       [59, 57, 60, 53, 57],
       [55, 47, 50, 73, 44],
       [37, 75, 50, 54, 55],
       [29, 47, 57, 61, 53],
       [54, 34, 39, 40, 55],
       [41, 69, 49, 58, 49],
       [37, 71, 47, 27, 69],
       [68, 71, 48, 44, 50],
       [56, 61, 66, 45, 55],
       [46, 48, 49, 56, 42],
       [45, 45, 33, 62, 45],
       [54, 51, 57, 49, 71],
       [52, 58, 57, 45, 39],
       [47, 48, 64, 57, 74],
       [40, 66, 47, 54, 44],
       [60, 55, 53, 57, 47],
       [44, 33, 49, 63, 53],
       [68, 44, 70, 46, 51],
       [49, 76

In [36]:
import numpy as np
data = np.random.randn(50,5)
intData = data * 10 + 50
newData = intData.astype(np.int64)
newData

array([[46, 72, 55, 54, 45],
       [43, 48, 44, 42, 25],
       [53, 51, 55, 41, 52],
       [58, 45, 53, 43, 52],
       [54, 54, 42, 46, 24],
       [43, 52, 54, 46, 48],
       [48, 55, 63, 43, 35],
       [52, 47, 55, 48, 57],
       [35, 47, 63, 50, 51],
       [58, 49, 39, 60, 27],
       [49, 53, 41, 48, 48],
       [53, 58, 39, 38, 49],
       [53, 36, 42, 41, 59],
       [27, 56, 63, 53, 55],
       [46, 56, 46, 38, 47],
       [46, 49, 39, 49, 56],
       [49, 50, 53, 32, 58],
       [38, 57, 40, 42, 47],
       [43, 42, 45, 58, 58],
       [51, 37, 72, 62, 41],
       [36, 61, 43, 62, 46],
       [52, 52, 39, 47, 48],
       [49, 56, 54, 54, 39],
       [53, 42, 54, 55, 40],
       [51, 48, 55, 40, 57],
       [45, 52, 48, 52, 36],
       [58, 54, 54, 47, 42],
       [44, 50, 59, 39, 38],
       [61, 46, 46, 24, 51],
       [51, 54, 44, 58, 57],
       [64, 49, 50, 62, 58],
       [41, 47, 55, 63, 54],
       [66, 40, 40, 46, 48],
       [46, 41, 45, 40, 51],
       [55, 37

In [39]:
#zeros()
np.zeros((2,3),dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0]])

In [41]:
np.ones((2,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1]])

In [43]:
np.arange(2, 50)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])