In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 15.7 ms, sys: 5.76 ms, total: 21.4 ms
Wall time: 20.2 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 672 ms, sys: 228 ms, total: 899 ms
Wall time: 922 ms


In [8]:
#list轉為ndarray
a = np.array([1, 3, 5, 7, 9])
b = np.array([3, 5, 6, 7, 9])
c = a + b
print(c)

print(type(c))

[ 4  8 11 14 18]
<class 'numpy.ndarray'>


In [7]:
[1, 3, 5, 7, 9] + [3, 5, 6, 7, 9]

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [16]:
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)

[ 4  8 11 14 18]
1
(5,)
5
int64


In [18]:
ml = [[1,2,3],[4,5,6]]
ml[0][2]

3

In [19]:
ndml = np.array(ml)
print(ndml)
print(ndml.ndim)
print(ndml.shape)
print(ndml.size)
print(ndml.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64
