In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 16.9 ms, sys: 5.53 ms, total: 22.4 ms
Wall time: 21.2 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 665 ms, sys: 209 ms, total: 874 ms
Wall time: 883 ms


In [4]:
#list轉為ndarray
a = np.array([1, 3, 5, 7, 9])
b = np.array([3, 5, 6, 7, 9])
c = a + b
print(c)

print(type(c))

[ 4  8 11 14 18]
<class 'numpy.ndarray'>


In [5]:
[1, 3, 5, 7, 9] + [3, 5, 6, 7, 9]

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [6]:
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)

[ 4  8 11 14 18]
1
(5,)
5
int64


In [7]:
ml = [[1,2,3],[4,5,6]]
ml[0][2]

3

In [8]:
ndml = np.array(ml)
print(ndml)
print(ndml.ndim)
print(ndml.shape)
print(ndml.size)
print(ndml.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [9]:
import random
random.randint(1,10)

6

In [10]:
import numpy as np
data = np.random.randn(50,5)
print(data)
print(data * 10 + 50)
print(data.ndim)
print(data.shape)
print(data.dtype)

data = data * 10 + 50

newData = data.astype(np.int64)
newData

[[ 0.55290111 -0.89699395 -0.60451881  0.9338497  -0.2651453 ]
 [ 0.60117611  0.22107289  0.14727527  0.87002914  0.73433073]
 [-0.05647413 -0.5560972  -0.3261356   1.15603857 -0.43935461]
 [-1.55891435 -0.84507818 -1.90737083  0.98064657 -1.36137077]
 [ 1.09136528 -1.05113323 -0.97337524  1.60536704  0.12150093]
 [ 0.81576406  0.15666804 -0.15447796 -1.09871366 -0.09895002]
 [-0.29503782  1.62576957 -1.43296218  0.02625492  1.25987669]
 [-0.468186    1.99093745 -0.58764348 -2.16370817  1.17178224]
 [ 0.52379899 -0.73397456  0.47565126  0.79934739 -0.38590578]
 [-1.65040898 -0.32718588 -1.72584059 -0.36290513 -1.34910042]
 [ 0.94227742  0.78454258 -0.17986587 -0.35045323 -0.54664418]
 [ 1.45618506 -0.32557442  1.20544828 -0.66693512  1.11512444]
 [ 0.39494041  0.52863991 -1.37447841 -0.31417252  0.74325595]
 [-0.30089056 -1.1917193  -1.02291561 -0.96862746 -0.12856388]
 [-1.71961213  0.78521221 -0.71608846 -0.79598999 -1.94695686]
 [ 0.04296335 -0.938042    1.04209182 -0.00990062  1.31

array([[55, 41, 43, 59, 47],
       [56, 52, 51, 58, 57],
       [49, 44, 46, 61, 45],
       [34, 41, 30, 59, 36],
       [60, 39, 40, 66, 51],
       [58, 51, 48, 39, 49],
       [47, 66, 35, 50, 62],
       [45, 69, 44, 28, 61],
       [55, 42, 54, 57, 46],
       [33, 46, 32, 46, 36],
       [59, 57, 48, 46, 44],
       [64, 46, 62, 43, 61],
       [53, 55, 36, 46, 57],
       [46, 38, 39, 40, 48],
       [32, 57, 42, 42, 30],
       [50, 40, 60, 49, 63],
       [48, 40, 49, 62, 52],
       [64, 53, 55, 63, 52],
       [63, 44, 41, 72, 53],
       [37, 42, 49, 38, 35],
       [62, 65, 43, 51, 50],
       [61, 48, 48, 51, 49],
       [49, 51, 74, 58, 57],
       [48, 49, 34, 48, 38],
       [56, 49, 64, 62, 63],
       [70, 42, 43, 46, 45],
       [47, 48, 37, 46, 24],
       [35, 65, 40, 58, 59],
       [50, 51, 59, 31, 39],
       [55, 56, 39, 41, 50],
       [41, 34, 48, 66, 54],
       [52, 42, 37, 41, 51],
       [65, 58, 47, 50, 45],
       [57, 50, 51, 43, 53],
       [55, 47

In [11]:
import numpy as np
data = np.random.randn(50,5)
intData = data * 10 + 50
newData = intData.astype(np.int64)
for d in newData:
    print("學生總分:{:d},學生平均:{:.2f}".format(d.sum(),d.mean()))
print("全班總分:{:d},全型平均:{:.2f}".format(newData.sum(),newData.mean()))

學生總分:219,學生平均:43.80
學生總分:207,學生平均:41.40
學生總分:250,學生平均:50.00
學生總分:230,學生平均:46.00
學生總分:205,學生平均:41.00
學生總分:262,學生平均:52.40
學生總分:219,學生平均:43.80
學生總分:248,學生平均:49.60
學生總分:220,學生平均:44.00
學生總分:224,學生平均:44.80
學生總分:272,學生平均:54.40
學生總分:267,學生平均:53.40
學生總分:258,學生平均:51.60
學生總分:275,學生平均:55.00
學生總分:258,學生平均:51.60
學生總分:269,學生平均:53.80
學生總分:246,學生平均:49.20
學生總分:229,學生平均:45.80
學生總分:272,學生平均:54.40
學生總分:269,學生平均:53.80
學生總分:259,學生平均:51.80
學生總分:253,學生平均:50.60
學生總分:275,學生平均:55.00
學生總分:277,學生平均:55.40
學生總分:251,學生平均:50.20
學生總分:226,學生平均:45.20
學生總分:240,學生平均:48.00
學生總分:254,學生平均:50.80
學生總分:276,學生平均:55.20
學生總分:266,學生平均:53.20
學生總分:218,學生平均:43.60
學生總分:285,學生平均:57.00
學生總分:256,學生平均:51.20
學生總分:265,學生平均:53.00
學生總分:236,學生平均:47.20
學生總分:226,學生平均:45.20
學生總分:249,學生平均:49.80
學生總分:247,學生平均:49.40
學生總分:248,學生平均:49.60
學生總分:240,學生平均:48.00
學生總分:236,學生平均:47.20
學生總分:271,學生平均:54.20
學生總分:198,學生平均:39.60
學生總分:296,學生平均:59.20
學生總分:233,學生平均:46.60
學生總分:236,學生平均:47.20
學生總分:269,學生平均:53.80
學生總分:268,學生平均:53.60
學生總分:262,學生平均:52.40
學生總分:262,學生平均:52.40


In [12]:
#zeros()
np.zeros((2,3),dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
np.ones((2,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
np.arange(2, 50)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [15]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5]

5

In [17]:
arr[5:8]

array([5, 6, 7])

In [18]:
arr2d = np.array([[1,2,3],[4, 5, 6],[7, 8, 9]])
arr2d
arr2d.shape

(3, 3)

In [19]:
arr2d[2]

array([7, 8, 9])

In [20]:
arr2d[0][2]

3

In [21]:
arr2d[0,2]

3

In [22]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [23]:
arr2d1=arr2d[:2]
print(arr2d1)
arr2d1.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [24]:
arr2d2 = arr2d[:2, 1:]
print(arr2d2)
arr2d2.shape

[[2 3]
 [5 6]]


(2, 2)

In [25]:
#陣列初始化與重新規劃
import numpy as np
x = np.linspace(1,10,6)
y = x.reshape((2,3))
y

array([[ 1. ,  2.8,  4.6],
       [ 6.4,  8.2, 10. ]])

In [26]:
x = np.linspace(1, 10, 6).reshape((2, 3))
x

array([[ 1. ,  2.8,  4.6],
       [ 6.4,  8.2, 10. ]])

In [27]:
y = np.arange(100).reshape((50,2))
y

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59],
       [60, 61],
       [62, 63],
       [64, 65],
       [66, 67],
       [68, 69],
       [70, 71],
       [72, 73],
       [74, 75],
       [76, 77],
       [78, 79],
       [80, 81],
       [82, 83],
       [84, 85],
       [86, 87],
       [88, 89],
       [90, 91],
       [92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])

In [28]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [29]:
data = np.random.randn(7,4)
data

array([[-0.44188213,  0.15603295,  0.88767862,  0.30661233],
       [-2.07303401, -1.04480249, -0.0770781 , -2.16729487],
       [-0.08602685, -0.27506197, -0.48460833,  1.05166941],
       [ 0.86311139, -0.03822666, -1.07295764, -0.24020453],
       [ 1.03074802, -0.15101466, -1.27148118,  0.70480466],
       [-0.35729837, -1.27420306, -0.09664322,  0.86077153],
       [ 1.35424439,  0.29327153, -0.14519435,  0.03967922]])

In [30]:
data[names == 'Bob']

array([[-0.44188213,  0.15603295,  0.88767862,  0.30661233],
       [ 0.86311139, -0.03822666, -1.07295764, -0.24020453]])

In [31]:
data[names == 'Will']

array([[-0.08602685, -0.27506197, -0.48460833,  1.05166941],
       [ 1.03074802, -0.15101466, -1.27148118,  0.70480466]])

In [32]:
data[names == 'Joe']

array([[-2.07303401, -1.04480249, -0.0770781 , -2.16729487],
       [-0.35729837, -1.27420306, -0.09664322,  0.86077153],
       [ 1.35424439,  0.29327153, -0.14519435,  0.03967922]])

In [33]:
data < 0

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True, False],
       [False, False,  True, False]])

In [34]:
data[data<0] = 2
data

array([[2.        , 0.15603295, 0.88767862, 0.30661233],
       [2.        , 2.        , 2.        , 2.        ],
       [2.        , 2.        , 2.        , 1.05166941],
       [0.86311139, 2.        , 2.        , 2.        ],
       [1.03074802, 2.        , 2.        , 0.70480466],
       [2.        , 2.        , 2.        , 0.86077153],
       [1.35424439, 0.29327153, 2.        , 0.03967922]])

In [35]:
arr = np.random.randn(4, 4)
arr

array([[-0.3280738 ,  0.08023543,  0.01845786,  0.38355561],
       [-0.65999028, -1.57768613, -0.43501684,  1.3604112 ],
       [ 0.0304126 , -0.18198644,  0.92052479,  1.32611662],
       [ 0.67118217, -0.5654022 ,  0.48647332, -0.70539392]])

In [36]:
np.where(arr>0, 2, -2)

array([[-2,  2,  2,  2],
       [-2, -2, -2,  2],
       [ 2, -2,  2,  2],
       [ 2, -2,  2, -2]])

In [37]:
np.where(arr>0, 2, arr) 

array([[-0.3280738 ,  2.        ,  2.        ,  2.        ],
       [-0.65999028, -1.57768613, -0.43501684,  2.        ],
       [ 2.        , -0.18198644,  2.        ,  2.        ],
       [ 2.        , -0.5654022 ,  2.        , -0.70539392]])

In [38]:
#10個同學,每個同學5個分數
import numpy as np
arr = np.random.randint(50,101, size=(10, 5))
arr

array([[82, 65, 61, 73, 59],
       [87, 83, 51, 52, 58],
       [61, 70, 96, 95, 85],
       [81, 84, 73, 60, 99],
       [94, 99, 67, 93, 81],
       [63, 91, 93, 80, 52],
       [99, 99, 67, 71, 79],
       [59, 82, 62, 73, 56],
       [54, 60, 81, 78, 79],
       [60, 51, 74, 52, 96]])

In [39]:
arr.sum()

3720

In [40]:
arr.mean()

74.4

In [41]:
#標準差
arr.std()

15.164432069813891

In [42]:
arr.std(axis=1)

array([ 8.48528137, 15.58717421, 13.83618445, 12.84678948, 11.53082824,
       15.96746692, 13.62350909,  9.68710483, 11.14629983, 16.84755175])

In [43]:
arr.sum(axis=1)

array([340, 331, 407, 397, 434, 379, 415, 332, 352, 333])

In [44]:
arr.mean(axis=1)

array([68. , 66.2, 81.4, 79.4, 86.8, 75.8, 83. , 66.4, 70.4, 66.6])

In [45]:
arr.mean(axis=0)

array([74. , 78.4, 72.5, 72.7, 74.4])