In [1]:
#建立50位學生的中文和英文的分數
import random
chinese = [random.randint(60,100) for _ in range(50)]
english = [random.randint(60,100) for _ in range(50)]
print('chinese',chinese)
print('english',english)

chinese [86, 92, 88, 86, 71, 77, 90, 97, 78, 78, 84, 62, 92, 75, 66, 68, 77, 89, 65, 86, 91, 61, 95, 64, 86, 81, 83, 98, 79, 82, 94, 87, 60, 63, 69, 82, 93, 97, 74, 90, 73, 80, 64, 65, 93, 99, 77, 91, 87, 74]
english [84, 71, 75, 62, 66, 75, 96, 81, 88, 90, 100, 61, 94, 63, 88, 69, 90, 87, 76, 88, 96, 62, 90, 90, 96, 85, 78, 75, 65, 95, 77, 80, 70, 98, 84, 74, 68, 67, 62, 82, 62, 90, 69, 67, 71, 69, 89, 80, 68, 69]


In [3]:
results = [chinese[i]+english[i] for i in range(50)]
print(results)

[170, 163, 163, 148, 137, 152, 186, 178, 166, 168, 184, 123, 186, 138, 154, 137, 167, 176, 141, 174, 187, 123, 185, 154, 182, 166, 161, 173, 144, 177, 171, 167, 130, 161, 153, 156, 161, 164, 136, 172, 135, 170, 133, 132, 164, 168, 166, 171, 155, 143]


In [5]:
import numpy as np
ndChinese = np.array(chinese)
print(ndChinese.__class__)
ndEnglish = np.array(english)
print(ndChinese.__class__)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
ndChinese + ndEnglish

array([170, 163, 163, 148, 137, 152, 186, 178, 166, 168, 184, 123, 186,
       138, 154, 137, 167, 176, 141, 174, 187, 123, 185, 154, 182, 166,
       161, 173, 144, 177, 171, 167, 130, 161, 153, 156, 161, 164, 136,
       172, 135, 170, 133, 132, 164, 168, 166, 171, 155, 143])

In [7]:
import numpy as np
lis = [[1,2,3],[4,5,6]]
nda = np.array(lis)
nda

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
nda.ndim

2

In [9]:
nda.shape

(2, 3)

In [10]:
nda.size

6

In [11]:
nda.dtype

dtype('int64')

In [14]:
data = np.random.randn(2, 3)
data

array([[ 0.83746173, -0.25547397,  0.10641552],
       [ 0.21518012, -0.20313292, -0.87770629]])

In [16]:
#數學運算
data * 10

array([[ 8.37461735, -2.55473966,  1.06415521],
       [ 2.15180117, -2.0313292 , -8.77706294]])

In [18]:
data += data
data

array([[ 1.67492347, -0.51094793,  0.21283104],
       [ 0.43036023, -0.40626584, -1.75541259]])

In [19]:
#np.arange(12)
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
a.shape

(12,)

In [21]:
b = a.reshape((3,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
b[2,1]

9

In [23]:
arr = np.random.randint(50,101, size=(10,5))
arr

array([[ 77,  57,  73,  70, 100],
       [ 58,  50,  67,  85,  85],
       [ 77,  67,  98,  72,  57],
       [ 70,  74,  92,  53,  64],
       [ 96,  76,  63,  51,  56],
       [ 94,  97,  98,  50,  78],
       [ 85,  77,  87,  90,  51],
       [ 88,  84,  95,  87,  76],
       [ 87,  74,  72,  95,  56],
       [ 50,  88,  92,  55,  89]])

In [24]:
#加總
arr.sum()

3783

In [25]:
#平均
arr.mean()

75.66

In [26]:
#標準差
arr.std()

15.464294358295176

In [27]:
#每個學生的總分
arr.sum(axis=1)

array([377, 345, 371, 353, 342, 417, 390, 430, 384, 374])

In [30]:
#每個學生的平均
studentAVG = arr.mean(axis=1)

In [31]:
#全班最高平均
studentAVG.max()

86.0

In [32]:
#全班最低平均
studentAVG.min()

68.4