In [1]:

#建立50位學生的中文和英文的分數
import random
chinese = [random.randint(60,100) for _ in range(50)]
english = [random.randint(60,100) for _ in range(50)]
print('chinese',chinese)
print('english',english)

chinese [80, 73, 66, 92, 74, 86, 60, 73, 73, 74, 66, 68, 85, 76, 90, 86, 88, 64, 91, 88, 94, 71, 94, 89, 100, 84, 92, 65, 72, 97, 61, 88, 93, 79, 64, 87, 88, 90, 95, 100, 88, 67, 78, 89, 69, 94, 73, 63, 76, 86]
english [96, 89, 64, 74, 78, 67, 69, 95, 61, 84, 60, 69, 67, 78, 96, 83, 70, 83, 82, 75, 80, 83, 72, 69, 82, 77, 78, 95, 71, 69, 69, 91, 99, 66, 74, 87, 65, 67, 84, 76, 80, 65, 93, 60, 61, 88, 72, 77, 71, 89]


In [2]:
results = [chinese[i]+english[i] for i in range(50)]
print(results)

[176, 162, 130, 166, 152, 153, 129, 168, 134, 158, 126, 137, 152, 154, 186, 169, 158, 147, 173, 163, 174, 154, 166, 158, 182, 161, 170, 160, 143, 166, 130, 179, 192, 145, 138, 174, 153, 157, 179, 176, 168, 132, 171, 149, 130, 182, 145, 140, 147, 175]


In [3]:
import numpy as np

In [4]:

import numpy as np
ndChinese = np.array(chinese)
print(ndChinese.__class__)
ndEnglish = np.array(english)
print(ndChinese.__class__)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [5]:

ndChinese + ndEnglish

array([176, 162, 130, 166, 152, 153, 129, 168, 134, 158, 126, 137, 152,
       154, 186, 169, 158, 147, 173, 163, 174, 154, 166, 158, 182, 161,
       170, 160, 143, 166, 130, 179, 192, 145, 138, 174, 153, 157, 179,
       176, 168, 132, 171, 149, 130, 182, 145, 140, 147, 175])

In [13]:
import numpy as np
lis = [[1,2,3],[4,5,6]]
nda = np.array(lis)
nda

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
nda.ndim

2

In [10]:

nda.shape

(3, 3)

In [11]:
nda.size

9

In [14]:
nda.dtype

dtype('int32')

In [15]:
data = np.random.randn(2, 3)
data

array([[-0.21567801, -0.25622533, -0.75762556],
       [ 0.2911963 ,  1.887498  , -0.54385862]])

In [16]:
#數學運算
data * 10

array([[-2.15678009, -2.56225327, -7.57625555],
       [ 2.91196295, 18.87497997, -5.43858618]])

In [17]:
data += data
data

array([[-0.43135602, -0.51245065, -1.51525111],
       [ 0.58239259,  3.77499599, -1.08771724]])

In [18]:
#np.arange(12)
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
a.shape

(12,)

In [20]:
b = a.reshape((3,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:

b[2,1]

9

In [22]:
arr = np.random.randint(50,101, size=(10,5))
arr

array([[66, 59, 88, 76, 77],
       [99, 64, 73, 74, 86],
       [74, 58, 61, 60, 89],
       [54, 94, 82, 79, 76],
       [66, 78, 71, 90, 99],
       [71, 86, 68, 67, 77],
       [68, 67, 53, 53, 91],
       [83, 75, 59, 57, 61],
       [86, 76, 66, 60, 59],
       [96, 57, 58, 66, 87]])

In [23]:
#加總
arr.sum()

3640

In [24]:
#平均
arr.mean()

72.8

In [25]:

#標準差
arr.std()

12.781236246936366

In [26]:
#每個學生的總分
arr.sum(axis=1)

array([366, 396, 342, 385, 404, 369, 332, 335, 347, 364])

In [27]:
#每個學生的平均
studentAVG = arr.mean(axis=1)

In [28]:
#全班最高平均
studentAVG.max()

80.8

In [29]:
#全班最低平均
studentAVG.min()

66.4