In [1]:
#建立50位學生的中文和英文的分數
import random
chinese = [random.randint(60,100) for _ in range(50)]
english = [random.randint(60,100) for _ in range(50)]
print('chinese',chinese)
print('english',english)

chinese [86, 92, 88, 86, 71, 77, 90, 97, 78, 78, 84, 62, 92, 75, 66, 68, 77, 89, 65, 86, 91, 61, 95, 64, 86, 81, 83, 98, 79, 82, 94, 87, 60, 63, 69, 82, 93, 97, 74, 90, 73, 80, 64, 65, 93, 99, 77, 91, 87, 74]
english [84, 71, 75, 62, 66, 75, 96, 81, 88, 90, 100, 61, 94, 63, 88, 69, 90, 87, 76, 88, 96, 62, 90, 90, 96, 85, 78, 75, 65, 95, 77, 80, 70, 98, 84, 74, 68, 67, 62, 82, 62, 90, 69, 67, 71, 69, 89, 80, 68, 69]


In [3]:
results = [chinese[i]+english[i] for i in range(50)]
print(results)

[170, 163, 163, 148, 137, 152, 186, 178, 166, 168, 184, 123, 186, 138, 154, 137, 167, 176, 141, 174, 187, 123, 185, 154, 182, 166, 161, 173, 144, 177, 171, 167, 130, 161, 153, 156, 161, 164, 136, 172, 135, 170, 133, 132, 164, 168, 166, 171, 155, 143]


In [5]:
import numpy as np
ndChinese = np.array(chinese)
print(ndChinese.__class__)
ndEnglish = np.array(english)
print(ndChinese.__class__)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
ndChinese + ndEnglish

array([170, 163, 163, 148, 137, 152, 186, 178, 166, 168, 184, 123, 186,
       138, 154, 137, 167, 176, 141, 174, 187, 123, 185, 154, 182, 166,
       161, 173, 144, 177, 171, 167, 130, 161, 153, 156, 161, 164, 136,
       172, 135, 170, 133, 132, 164, 168, 166, 171, 155, 143])

In [7]:
import numpy as np
lis = [[1,2,3],[4,5,6]]
nda = np.array(lis)
nda

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
nda.ndim

2

In [9]:
nda.shape

(2, 3)

In [10]:
nda.size

6

In [11]:
nda.dtype

dtype('int64')

In [14]:
data = np.random.randn(2, 3)
data

array([[ 0.83746173, -0.25547397,  0.10641552],
       [ 0.21518012, -0.20313292, -0.87770629]])

In [16]:
#數學運算
data * 10

array([[ 8.37461735, -2.55473966,  1.06415521],
       [ 2.15180117, -2.0313292 , -8.77706294]])

In [18]:
data += data
data

array([[ 1.67492347, -0.51094793,  0.21283104],
       [ 0.43036023, -0.40626584, -1.75541259]])