## Numpy建立與計算

### 陣列初始與規劃
1. 陣列初始化
2. 陣列重新規劃
3. 計算與取代

### 指定與重設
1. 一個整數指定
2. tuple 或 list 指定
3. 重設陣列

### 數值計算與處理
1. 數值計算
2. 總和最大與最小
3. 中位數與平均

###  NP 陣列的基本屬性
1. ndarray.ndim - 維度的數量。
2. ndarray.shape - 顯示出陣列在每個維度上的整數值。
3. ndarray.size - 陣列內元素的總數。
4. ndarray.dtype - 來描述陣列中元素類型的對象。

#### 操作檔案
- num2.py

In [1]:
import numpy as np
l = [[1, 2, 3],
    [2, 3, 4]]
a = np.array(l)
print(a)
print("number of dim:",a.ndim)
print("shape:",a.shape)
print("size:",a.size)
print("size:",a.dtype)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6
size: int64


###  陣列初始化與重新規劃
#### 針對初始化這部分提供了多種方式:
- 不做初始化 - 例如:np.empty((2,4))
- 全部規劃為 0 - 例如:np.zeros((3,4))
- 全部規劃為 1 - 例如: np.ones((5,2))
- 全部規劃/填滿為某數，例如 6 - 例如: np.full((3,3),6)
- 建立對角矩陣，對角皆為 1，其他為 0 - 例如: np.eye(3)
- 建立對角矩陣，對角為 1,2,3,4，其他為 0 - 例如: np.diag([1,2,3,4])
- reshape((x,y)) 這個指令就可以將現有的陣列重新規劃為 x 乘以 y 的陣列。
- np.arange(起始值, 結束值, 固定間隔):也是產生一維陣列，和 np.array( ) 的差別在於 arange 擁有較大的彈性，而且元素數值是自 動化產生。
- np.linspace(起始值, 結束值, 起始與結束的區間內要產生幾個元素 ): 只要給定陣列的區間(起始值、結束值)，就可以要求在這個區間內產 生幾個元素。
- arange(a,b,c) - 不包含 b 由 a 開始 以固定間隔 c 來取值
- linspace(a,b,c,) - 包含 b 由 a 開始 切割成 c 個資料
- linspace(a,b,c,endpoint=False) - 不包含 b 由 a 開始 切割成 c 個資料

####  操作範例 1:陣列初始化與重新規劃
- num2b.py

In [2]:
import numpy as np
x=np.empty((2,4))
print(x)
print("-----")
x =np.zeros((3,4))
print(x)
print("-----")
c = np.ones((5,2))
print(c)

[[-1.28822975e-231  1.73060157e-077  1.97626258e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  5.56268465e-309]]
-----
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


####  操作範例 2:陣列初始化與重新規劃
- num2c.py

In [4]:
import numpy as np
x=np.eye(3)
print(x)
print("-----")
x =np.diag([1,2,3,4]) 
print(x)
print("-----")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
-----


####  操作範例 3:陣列初始化與重新規劃
- num2c1.py

In [2]:
import numpy as np
x = np.linspace(1,10,6).reshape((3,2)) 
print(x)
print("-----")
x = np.linspace(1,10,6).reshape((2,3)) 
print(x)
print("-----")
x =np.arange(8).reshape((2,4)) 
print(x)
print("-----")
x =np.arange(8).reshape((4,2)) 
print(x)
print("-----")

[[ 1.   2.8]
 [ 4.6  6.4]
 [ 8.2 10. ]]
-----
[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
-----
[[0 1 2 3]
 [4 5 6 7]]
-----
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
-----


####  請問以下的程式執行後值是多少?(選擇題)

```python
import numpy as np
r1 = np.arange(25, 30, .5) 
print("r1=>",r1)
```
(1) 30  
(2) 29.5  
(3) 25  
(4) 27  


####  請問以下的程式執行後值是多少?(選擇題)

```python
import numpy as np
lin = np.linspace(3, 5, 9) 
print("r1=>",lin)
```
(1) 9   
(2) 8.5   
(3) 8  
(4) 5   

####  操作範例:陣列初始化與重新規劃
- num2e.py

In [4]:
import numpy as np
a = np.array( [6, 7, 8, 9] ) 
b = np.arange( 4 )
c=a-b
print("a=>",a) 
print("b=>",b) 
print("c=>",c)
d = b**2
print("d=>",d)
f = np.array([5, -1, 3, 9, 0]) 
f[f<=3] = 1
print("f=>",f)

a=> [6 7 8 9]
b=> [0 1 2 3]
c=> [6 6 6 6]
d=> [0 1 4 9]
f=> [5 1 1 9 1]
