## Numpy建立與計算

### 陣列初始與規劃
1. 陣列初始化
2. 陣列重新規劃
3. 計算與取代

### 指定與重設
1. 一個整數指定
2. tuple 或 list 指定
3. 重設陣列

### 數值計算與處理
1. 數值計算
2. 總和最大與最小
3. 中位數與平均

###  NP 陣列的基本屬性
1. ndarray.ndim - 維度的數量。
2. ndarray.shape - 顯示出陣列在每個維度上的整數值。
3. ndarray.size - 陣列內元素的總數。
4. ndarray.dtype - 來描述陣列中元素類型的對象。

In [1]:
# 操作檔案
# num2.py
import numpy as np
l = [[1, 2, 3],
    [2, 3, 4]]
a = np.array(l)
print(a)
print("number of dim:",a.ndim)
print("shape:",a.shape)
print("size:",a.size)
print("size:",a.dtype)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6
size: int64


###  陣列初始化與重新規劃
#### 針對初始化這部分提供了多種方式:
- 不做初始化 - 例如:np.empty((2,4))
- 全部規劃為 0 - 例如:np.zeros((3,4))
- 全部規劃為 1 - 例如: np.ones((5,2))
- 全部規劃/填滿為某數，例如 6 - 例如: np.full((3,3),6)
- 建立對角矩陣，對角皆為 1，其他為 0 - 例如: np.eye(3)
- 建立對角矩陣，對角為 1,2,3,4，其他為 0 - 例如: np.diag([1,2,3,4])
- reshape((x,y)) 這個指令就可以將現有的陣列重新規劃為 x 乘以 y 的陣列。
- np.arange(起始值, 結束值, 固定間隔):也是產生一維陣列，和 np.array( ) 的差別在於 arange 擁有較大的彈性，而且元素數值是自 動化產生。
- np.linspace(起始值, 結束值, 起始與結束的區間內要產生幾個元素 ): 只要給定陣列的區間(起始值、結束值)，就可以要求在這個區間內產 生幾個元素。
- arange(a,b,c) - 不包含 b 由 a 開始 以固定間隔 c 來取值
- linspace(a,b,c,) - 包含 b 由 a 開始 切割成 c 個資料
- linspace(a,b,c,endpoint=False) - 不包含 b 由 a 開始 切割成 c 個資料

In [2]:
# 操作範例 1:陣列初始化與重新規劃
# num2b.py
import numpy as np
x=np.empty((2,4))
print(x)
print("-----")
x =np.zeros((3,4))
print(x)
print("-----")
c = np.ones((5,2))
print(c)


[[-1.28822975e-231  1.73060157e-077  1.97626258e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  5.56268465e-309]]
-----
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
# 操作範例 2:陣列初始化與重新規劃
# num2c.py
import numpy as np
x=np.eye(3)
print(x)
print("-----")
x =np.diag([1,2,3,4]) 
print(x)
print("-----")


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
-----


In [2]:
# 操作範例 3:陣列初始化與重新規劃
# num2c1.py
import numpy as np
x = np.linspace(1,10,6).reshape((3,2)) 
print(x)
print("-----")
x = np.linspace(1,10,6).reshape((2,3)) 
print(x)
print("-----")
x =np.arange(8).reshape((2,4)) 
print(x)
print("-----")
x =np.arange(8).reshape((4,2)) 
print(x)
print("-----")

[[ 1.   2.8]
 [ 4.6  6.4]
 [ 8.2 10. ]]
-----
[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
-----
[[0 1 2 3]
 [4 5 6 7]]
-----
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
-----


####  請問以下的程式執行後值是多少?(選擇題)

```python
import numpy as np
r1 = np.arange(25, 30, .5) 
print("r1=>",r1)
```
(1) 30  
(2) 29.5  
(3) 25  
(4) 27  


####  請問以下的程式執行後值是多少?(選擇題)

```python
import numpy as np
lin = np.linspace(3, 5, 9) 
print("r1=>",lin)
```
(1) 9   
(2) 8.5   
(3) 8  
(4) 5   


In [4]:
# 操作範例:陣列初始化與重新規劃
# num2e.py
import numpy as np
a = np.array( [6, 7, 8, 9] ) 
b = np.arange( 4 )
c=a-b
print("a=>",a) 
print("b=>",b) 
print("c=>",c)
d = b**2
print("d=>",d)
f = np.array([5, -1, 3, 9, 0]) 
f[f<=3] = 1
print("f=>",f)

a=> [6 7 8 9]
b=> [0 1 2 3]
c=> [6 6 6 6]
d=> [0 1 4 9]
f=> [5 1 1 9 1]


####  請問以下的程式執行後值是多少?(選擇題)

```python
import numpy as np
a = np.array( [6, 7, 8, 9] ) 
a += 2
print(a)
```
(1) [2 8 9 10 11]  
(2) [8 9 10 11 2]  
(3) [8 9 10 11]  
(4) [6 7 8 9 6 7 8 9]  


## 指定與重設
1. 一個整數指定
2. tuple 或 list 指定
3. 重設陣列

###  陣列指定位置取值
1. 間隔選取[::C]
    - 以 1 維陣列來說明 x[a:b:c]  
    - a:選取資料的起始索引
    - b:選取資料的結束索引 +1
    - c:選取資料間隔，以索引值可以被此值整除的元素，不指定表示 1
2. 倒序 [::-1]
    - 只是單純的把順序反過來

###  陣列指定位置-給予一個整數
1. 關於指定位置 [row,column]
2. 假設給予一個整數為 N
    - 如果是給固定的 N，那就代表 row 或 column 等於 N。
    - 如果是 N:，那就代表 row 或 column 大於等於 N 的區域。
    - 如果是:N，那就代表 row 或 column 小於 N 的區域。
    - 如果是:，那就代表 row 或 column 是任意欄位。

  

In [1]:
# 陣列指定位置取值
# num1a.py

import numpy as np
a = np.array([[1, 2, 3], [3, 6, 9], [2, 4, 6]]) 
print(a)
print("---------------")
print(a[0])
print("---------------")
print(a[1, 2])
print("---------------")







[[1 2 3]
 [3 6 9]
 [2 4 6]]
---------------
[1 2 3]
---------------
9
---------------


In [2]:
# 陣列指定位置取值
# num1b.py
import numpy as np
a = np.array([[1, 2, 3], [3, 6, 9], [2, 4, 6]]) 
print(a[1, 1:3])
print("---------------")
print(a[:,1])
print("---------------")
a[1, 2] = 7
print(a)
print("---------------")
a[:, 0] = [0, 9, 8]
print(a)
print("---------------")




[6 9]
---------------
[2 6 4]
---------------
[[1 2 3]
 [3 6 7]
 [2 4 6]]
---------------
[[0 2 3]
 [9 6 7]
 [8 4 6]]
---------------


In [3]:
# 陣列指定位置取值
# num1c.py

import numpy as np 
a = np.array([
[0,1, 2, 3,4,5],
[10,11,12,13,14,15],
[20,21,22,23,24,25],
[30,31,32,33,34,35],
[40,41,42,43,44,45],
[50,51,52,53,54,55], 
])

print("--1--") 
print(a[0,3:5]) 
print("--2--") 
print(a[4:,4:]) 
print("--3--") 
print(a[:3,:3]) 
print("--4--") 
print(a[:,2])


--1--
[3 4]
--2--
[[44 45]
 [54 55]]
--3--
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
--4--
[ 2 12 22 32 42 52]


In [4]:
# 陣列指定位置取值
# num1d.py
import numpy as np 
a = np.array([
[0,1, 2, 3,4,5],
[10,11,12,13,14,15],
[20,21,22,23,24,25],
[30,31,32,33,34,35],
[40,41,42,43,44,45],
[50,51,52,53,54,55], 
])

print("--1--") 
print(a[(0,1,2,3,4),(1,2,3,4,5)]) 
print("--2--")
print(a[3:,[0, 2, 5]])

--1--
[ 1 12 23 34 45]
--2--
[[30 32 35]
 [40 42 45]
 [50 52 55]]


###  重設新陣列
1. resize 這個動作會依據原本的陣列再設定指定大小的新陣列。
2. resize 動作的參數如下:
    - numpy.resize(arr1，shape1)
    - arr1:原本的陣列
    - shape1:新規劃的大小
###  重設新陣列
1. 如果規劃的新陣列比較大，將會重新複製原有陣列的資料，填滿新的儲存格。
2. resize 這個動作建立新的陣列，而 reshape 則是依據原有的重新規劃，仍會受到原有陣列影響。

In [5]:
# 操作範例:reshape
# num5.py
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
print(a.shape)
print( )
b = a.reshape(3,2)
print(b)
print(b.shape)
print( )
a[0,1]=100
print(b)
print(b.shape)
print( )

[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[[  1 100]
 [  3   4]
 [  5   6]]
(3, 2)



In [6]:
# 操作範例:resize
# num5a.py
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
print(a.shape)
print( )
b = np.resize(a, (3,2)) 
print(b)
print(b.shape)
print( )
a[0,1]=100
print(b)
print(b.shape) 
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
(2, 3)


## 數值計算與處理
1. 數值計算
2. 總和最大與最小
3. 中位數與平均

###  數值計算
1. 數值計算函數內放入參與計算的兩個陣列。
2. 進行計算的陣列第一維數量必須是相同。
3. add( ) 方法代表「加」，也可以使用「+」。
4. subtract( ) 方法代表「減」，也可以使用「-」。
5. multiply( )方法代表「乘」，也可以使用「*」。
6. divide( ) 方法代表「除」，也可以使用「/」。

In [8]:
# 操作範例:數值計算
# num12.py

import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
b = np.array([10,10,10]) 
c=np.add(a,b)
print(c)
print( )

d= np.subtract(a,b)
print(d)
print( )

f=np.multiply(a,b) 
print(f)
print( ) 

g=np.divide(a,b) 
print(g)
print( )

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]

[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]



In [9]:
# 操作範例:數值計算
# num12a1.py

import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
b = np.array([10,10,10])

c=a+b
print(c)
print( )

d= a-b
print(d)
print( )

f=a*b 
print(f) 
print( ) 

g=a/b 
print(g) 
print( )


[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]

[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]



###  數值計算
1. np.power(a,n) 代表 a 陣列的 n 次方。
2. a 陣列的 n 次方也可以使用 a ** n 方式表示。
3. N 可以是陣列，但兩陣列第一維數量必須是相同。
4. np. Reciprocal( ) 代表倒數的計算，倒數是指a*b=1，輸入 a 後求 b。

In [10]:
# 操作範例:數值計算
# num12a2.py

import numpy as np 
a = np.array([4,5,6]) 
print(a)
print( )

b=np.power(a,2) 
print(b)
print( )

c = np.array([1,2,3]) 
d=np.power(a,c) 
print(d)
print( )

h=a**c
print(h)


[4 5 6]

[16 25 36]

[  4  25 216]

[  4  25 216]


In [ ]:
# 操作範例:數值計算
# num12a3.py

import numpy as np
a = np.array([0.25, 1.33, 1, -0.1, 100]) 
print(a)
print( )

b=np.reciprocal(a)
print(b)
print( )

###  除法計算與小數處理
1. np.mod( ) 方法內需加入兩個資料，例如 a 與 b，代表 a除以 b 的餘數。
2. np.remainder( ) 方法等同 np.mod( )。
3. np.around( ) 方法代表您要將浮點數資料整數位取四捨五入到第幾 個位置，小數位取最接近的偶數，這個方法內需要兩個參數:
    - array:進行分析的陣列。
    - decimals小數位數:
        - 預設為 0。
        - 如果為正數，代表小數位數有幾個位子。
        - 如果為負數，代表小數點左邊的正整數將依序四捨五入進位。

###  計算機浮點數問題
1. numpy [官網原文](https://docs.scipy.org/doc/numpy/reference/generated/numpy.around.html)
2. 關於計算機浮點數問題的文章
3. [“Lecture Notes on the Status of IEEE 754”, William Kahan](https://people.eecs.berkeley.edu/~wkahan/ieee754status/IEEE754.PDF)
4. 對於正好在舍入小數值之間的值，NumPy舍入到最接近的偶數值。 因此，1.5和 2.5捨入後為2.0，-0.5和0.5捨入後為到0.0等。由於IEEE浮點標準中的小數部分 的不精確表示以及當以10的冪進行縮放時產生的誤差。

In [1]:
# 操作範例:np.around 函數數值計算
# num_np_around.py

import numpy as np 
print(np.around([1.5, 2.5], decimals=0)) 
print(np.around([-0.5, 0.5], decimals=0))

[2. 2.]
[-0.  0.]


###  除法計算與小數處理
1. np.floor( ) 方法代表回傳不大於輸入參數的最大整數。
2. np.ceil( ) 方法代表回傳大於輸入參數的最小整數。

In [2]:
# 操作範例:除法計算與小數處理
# num12c.py

import numpy as np
a = np.array([10,20,30]) 
b = np.array([3,5,7]) 
print(a)
print( )

c=np.mod(a,b)
print(c)
print( ) 

d=np.remainder(a,b) 
print(d)
print( )

[10 20 30]

[1 0 2]

[1 0 2]



In [ ]:
# 操作範例:除法計算與小數處理
# num12d.py

import numpy as np
a = np.array([1.0,5.45, 123, 0.567, 25.532])
print(a)
print( )

b=np.around(a)
print(b)
print(np.around(a, decimals = 1) ) 
print(np.around(a, decimals = -1)) 
print(np.around(a, decimals = -2))

In [ ]:
# 操作範例:除法計算與小數處理
# num12e.py
import numpy as np
a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 
print(a)
print( )

b=np.floor(a)
print(b)
print( )

c=np.ceil(a)
print(c)
print( )

###  總和最大與最小
1. np.sum( ) 代表某一個陣列內容的總和，也可以指定這個陣列的哪一軸 (axis) 內容總和。
2. np.min( ) 代表某一個陣列內容的最小值，也可以指定這個陣列的哪一軸 (axis) 內容的最小值。
3. np.max( ) 代表某一個陣列內容的最大值，也可以指定這個陣列的哪一軸 (axis) 內容的最大值。
4. amin 與 min 是相同功能的方法。
5. amax 與 max 是相同功能的方法。

In [3]:
# 操作範例:總和最大與最小
# num13.py

import numpy as np
a = np.array([[0, 30,45],[60,75,90]]) 
print(a)
print("---------------")

b=np.sum(a)
print(b)
print("---------------") 

b=np.sum(a,axis=0)
print(b)
print("---------------") 

b=np.sum(a,axis=1)
print(b)
print("---------------")

[[ 0 30 45]
 [60 75 90]]
---------------
300
---------------
[ 60 105 135]
---------------
[ 75 225]
---------------


In [4]:
# 操作範例:總和最大與最小
# num13a1.py
import numpy as np
a = np.array([[0, 30,45],[60,75,90]]) 
print(a)
print("---------------")

b=np.max(a)
print(b)
print("---------------") 

b=np.max(a,axis=0)
print(b)
print("---------------") 

b=np.max(a,axis=1)
print(b)
print("---------------")

[[ 0 30 45]
 [60 75 90]]
---------------
90
---------------
[60 75 90]
---------------
[45 90]
---------------


###  中位數與平均
1. median( ) 方法可取出陣列或陣列中指定的軸之中位數。
2. 把所有值高低排序後找出正中間的一個作爲中位數。如果資料數量為偶數，則中位數取最中間的兩個數值的平均數。
3. 參數:
    - array:陣列
    - axis:軸
    
4. mean( ) 方法可取出陣列或陣列中指定的軸之平均數。 
5. 平均值就是把陣列或指定軸的所有資料除以數量後的數值。
6. 參數:
    - array:陣列
    - axis:軸

7. average( ) 方法與 mean( ) 方法相似，但可以加入權重進行計算。
8. 計算公式為 ((資料*權重)相加)/(權重相加)
9. 參數:
    - array:陣列
    - axis:軸
    - weights:權重，若沒有則設定為 1
    - returned:若設定為 true，代表返回計算結果與權重相加總合，若沒有設定或設定 false 則只有計算結果
10. 沒有指定權重時與一般平均值相同。
11. 加權平均值是由每個資料乘以權重以反映加上重要性因素後產生的平均值。
12. average( ) 使用時若沒有指定軸，則陣列將被平坦化。 
13. 假設有個陣列資料為 [1,2,3,4]，相應的權重 [40,30,20,10]，加權 平均數是這樣:
    -  (1*40+2*30+3*20+4*10)/(40+30+20+10)

In [ ]:
# 操作範例:中位數與平均
# num14.py

import numpy as np
a = np.array([[0, 30,45],[60,75,90]]) 
print(a)
print( )

b=np.median(a)
print(b)
print( )

b=np.median(a, axis = 0)
print(b)
print( )

b=np.median(a, axis = 1)
print(b)
print( )

In [ ]:
# 操作範例:中位數與平均
# num14a.py

import numpy as np
a = np.array([[0, 30,45],[60,75,90]]) 
print(a)
print( )

b=np.mean(a)
print(b)
print( )

b=np.mean(a, axis = 0)
print(b)
print( )

b=np.mean(a, axis = 1)
print(b)
print( )

In [ ]:
# 操作範例:中位數與平均
# num14b.py
import numpy as np
a = np.array([1,2,3,4])
b=np.average(a)
print(b)
print( )

wts = np.array([4,3,2,1])
b=np.average(a,weights = wts)
print(b)
print( )

b=np.average([1,2,3,4],weights = [4,3,2,1], returned = True)
print(b)
print( )

#### Homework 人數統計
1. [請到以下網頁查看](http://python2018.byethost10.com/class6.html)
2. 接著請您:
    - 利用迴圈跑出 17 個月各月的總人數。
    - 計算 17 個月的人口平均值、中位數、最大值與最小值。