In [4]:
import numpy as np

ndarray1 = np.arange(12)
ndarray1.shape

(12,)

In [5]:
ndarray_2_6= ndarray1.reshape(2,6)
ndarray_2_6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [6]:
ndarray_4_3 = ndarray1.reshape(4,3)
ndarray_4_3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
ndarray_2_2_3 = ndarray1.reshape(2,2,3)
ndarray_2_2_3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])