In [4]:
#index,slice
import numpy as np

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr2d[0,2]

3

In [6]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [7]:
import numpy as np 
students = np.random.randint(50,101,size=(50,5))
students

array([[ 57,  79,  80,  87,  91],
       [ 76,  76,  66,  59,  83],
       [ 79,  89,  51,  97,  76],
       [ 97,  69,  85,  64,  66],
       [ 56,  72,  69,  82,  76],
       [ 83,  84,  55,  94,  75],
       [ 57,  58,  68,  88,  94],
       [ 95,  97,  84,  83,  76],
       [ 63,  63,  52,  92,  92],
       [ 53,  89,  57,  96,  61],
       [ 99,  76,  52,  58,  50],
       [ 56,  62,  77,  73,  90],
       [ 81,  67,  59,  53,  52],
       [ 66,  82,  84,  98,  78],
       [ 57,  88, 100,  95,  53],
       [ 97,  99,  67,  93,  89],
       [ 95,  68,  85,  71,  54],
       [ 60,  53,  51,  50,  60],
       [ 73,  75, 100,  50,  83],
       [ 97,  87,  81,  77,  86],
       [ 61,  67,  54,  52,  92],
       [ 96,  91,  59,  71,  90],
       [ 57,  82,  99,  64,  62],
       [ 65,  96,  83, 100,  78],
       [ 78,  80,  61,  59,  64],
       [ 61,  80,  65,  68,  54],
       [ 96,  89,  85,  84,  82],
       [ 56,  58,  70,  54,  56],
       [ 61,  63,  94,  80,  57],
       [ 85,  

In [8]:
students.sum()

18649

In [9]:
students.mean()

74.596

In [10]:
students.std()

15.554831532356754

In [12]:
students.sum(axis=1)

array([394, 360, 392, 381, 355, 391, 365, 435, 362, 356, 335, 358, 312,
       408, 393, 445, 373, 274, 381, 428, 326, 407, 364, 422, 342, 328,
       436, 294, 355, 398, 395, 344, 369, 320, 390, 398, 393, 430, 358,
       419, 411, 385, 353, 390, 377, 414, 326, 367, 317, 323])

In [13]:
students.mean(axis=1)

array([78.8, 72. , 78.4, 76.2, 71. , 78.2, 73. , 87. , 72.4, 71.2, 67. ,
       71.6, 62.4, 81.6, 78.6, 89. , 74.6, 54.8, 76.2, 85.6, 65.2, 81.4,
       72.8, 84.4, 68.4, 65.6, 87.2, 58.8, 71. , 79.6, 79. , 68.8, 73.8,
       64. , 78. , 79.6, 78.6, 86. , 71.6, 83.8, 82.2, 77. , 70.6, 78. ,
       75.4, 82.8, 65.2, 73.4, 63.4, 64.6])