In [1]:
import numpy as np
list1 = [[1,2,3],
         [2,3,4]]

nd1 = np.array(list1)
nd1

array([[1, 2, 3],
       [2, 3, 4]])

In [2]:
#ndarray的屬性ndim
nd1.ndim

2

In [3]:
nd1.shape

(2, 3)

In [4]:
nd1.size

6

In [5]:
nd1.dtype

dtype('int64')

In [9]:
random_int = np.random.randint(1,100+1,size=(2,3))
print(random_int)


#ndarray的數學運算
print(random_int * 10)

print(random_int + random_int)

[[85 65 10]
 [22 36 30]]
[[850 650 100]
 [220 360 300]]
[[170 130  20]
 [ 44  72  60]]


In [11]:
print(np.arange(100))

print(np.arange(-3,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[-3 -2 -1  0  1  2]


In [16]:
x_linespace  = np.linspace(-3,3,50)
print(x_linespace)

print(len(x_linespace))



[-3.         -2.87755102 -2.75510204 -2.63265306 -2.51020408 -2.3877551
 -2.26530612 -2.14285714 -2.02040816 -1.89795918 -1.7755102  -1.65306122
 -1.53061224 -1.40816327 -1.28571429 -1.16326531 -1.04081633 -0.91836735
 -0.79591837 -0.67346939 -0.55102041 -0.42857143 -0.30612245 -0.18367347
 -0.06122449  0.06122449  0.18367347  0.30612245  0.42857143  0.55102041
  0.67346939  0.79591837  0.91836735  1.04081633  1.16326531  1.28571429
  1.40816327  1.53061224  1.65306122  1.7755102   1.89795918  2.02040816
  2.14285714  2.26530612  2.3877551   2.51020408  2.63265306  2.75510204
  2.87755102  3.        ]
50
