In [1]:
import numpy as np
list1 = [[1,2,3],
         [2,3,4]]

nd1 = np.array(list1)
nd1

array([[1, 2, 3],
       [2, 3, 4]])

In [2]:
#ndarray的屬性ndim
nd1.ndim

2

In [3]:
nd1.shape

(2, 3)

In [4]:
nd1.size

6

In [5]:
nd1.dtype

dtype('int64')

In [9]:
random_int = np.random.randint(1,100+1,size=(2,3))
print(random_int)


#ndarray的數學運算
print(random_int * 10)

print(random_int + random_int)

[[85 65 10]
 [22 36 30]]
[[850 650 100]
 [220 360 300]]
[[170 130  20]
 [ 44  72  60]]
