In [18]:
import pandas as pd
dataFrame=pd.read_csv('youbike.csv',encoding='big5')
dataFrame.reindex(range(1,361))

場站編號           站名 土木施工費用
1    500101003    國北教大實小東側門  5,456
2    500101004       和平公園東側  6,037
3    500101005    辛亥復興路口西北側  4,858
4    500101006  復興南路二段280號前  4,858
5    500101007  復興南路二段340巷口  8,993
..         ...          ...    ...
356  500112025         松友公園  5,821
357  500112026         林口公園  6,928
358  500112027         松山家商  6,928
359  500112028      永春陂濕地公園  6,928
360  500112037         春光公園  6,928

[360 rows x 3 columns]

In [3]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [4]:
obj.reindex(['a', 'b', 'c', 'd', 'e'])

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [11]:
import numpy as np
n1=np.arange(9)
print(n1)
print(n1.shape)
print(np.reshape(n1,(3,3)))
print(n1.reshape((3,3)))

[0 1 2 3 4 5 6 7 8]
(9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),
             index = ['a', 'c', 'd'],
             columns = ['台北', '台中', '高雄']
            )
frame

台北  台中  高雄
a   0   1   2
c   3   4   5
d   6   7   8

In [14]:
frame.reindex(['a','b','c','d'])

台北   台中   高雄
a  0.0  1.0  2.0
b  NaN  NaN  NaN
c  3.0  4.0  5.0
d  6.0  7.0  8.0

In [15]:
frame.reindex(['a','c'])

台北  台中  高雄
a   0   1   2
c   3   4   5

In [16]:
frame.reindex(['a','c'],columns=['台北','高雄','台南'])

台北   高雄  台南
a  0.0  2.0 NaN
c  3.0  5.0 NaN