In [27]:
import pandas as pd
dataFrame=pd.read_csv('youbike.csv',encoding='big5')
#dataFrame.reindex(range(1,361))
dataFrame.drop(0)

場站編號           站名 土木施工費用
1    500101003    國北教大實小東側門  5,456
2    500101004       和平公園東側  6,037
3    500101005    辛亥復興路口西北側  4,858
4    500101006  復興南路二段280號前  4,858
5    500101007  復興南路二段340巷口  8,993
..         ...          ...    ...
356  500112025         松友公園  5,821
357  500112026         林口公園  6,928
358  500112027         松山家商  6,928
359  500112028      永春陂濕地公園  6,928
360  500112037         春光公園  6,928

[360 rows x 3 columns]

In [3]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [4]:
obj.reindex(['a', 'b', 'c', 'd', 'e'])

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [19]:
import numpy as np
n1=np.arange(9)
print(n1)
print(n1.shape)
print(np.reshape(n1,(3,3)))
print(n1.reshape((3,3)))
n1.dtype

[0 1 2 3 4 5 6 7 8]
(9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


dtype('int64')

In [21]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),
             index = ['a', 'c', 'd'],
             columns = ['台北', '台中', '高雄']
            )
print(frame.dtypes)
frame

台北    int64
台中    int64
高雄    int64
dtype: object


台北  台中  高雄
a   0   1   2
c   3   4   5
d   6   7   8

In [22]:
frame1=frame.reindex(['a','b','c','d'])
print(frame1.dtypes)
frame1

台北    float64
台中    float64
高雄    float64
dtype: object


台北   台中   高雄
a  0.0  1.0  2.0
b  NaN  NaN  NaN
c  3.0  4.0  5.0
d  6.0  7.0  8.0

In [15]:
frame.reindex(['a','c'])

台北  台中  高雄
a   0   1   2
c   3   4   5

In [16]:
frame.reindex(['a','c'],columns=['台北','高雄','台南'])

台北   高雄  台南
a  0.0  2.0 NaN
c  3.0  5.0 NaN

In [23]:
#drop()
obj = pd.Series(np.arange(5.),index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [24]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [25]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [29]:
#drop()
#dataFrame
data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index = ['台北','台中', '台南', '高雄'],
                    columns = ['one', 'two', 'three', 'four']
                   )
data

one  two  three  four
台北    0    1      2     3
台中    4    5      6     7
台南    8    9     10    11
高雄   12   13     14    15

In [30]:
data.drop(['台南','高雄'])

one  two  three  four
台北    0    1      2     3
台中    4    5      6     7

In [32]:
data.drop(['one','two'],axis=1)

three  four
台北      2     3
台中      6     7
台南     10    11
高雄     14    15

In [35]:
data.drop(index=['台北','台中'],columns=['one','two'])

three  four
台南     10    11
高雄     14    15

In [36]:
#索引、選取、過濾¶
obj = pd.Series(np.arange(4.0), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [37]:
obj[0]

0.0

In [38]:
obj['a']

0.0

In [39]:
obj[['a', 'b', 'c']]

a    0.0
b    1.0
c    2.0
dtype: float64

In [40]:
obj[0:3]

a    0.0
b    1.0
c    2.0
dtype: float64

In [42]:
#過濾
obj[obj>=2]

c    2.0
d    3.0
dtype: float64

In [43]:
#索引、選取、過濾(DataFrame)
data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index = ['台北','台中','台南', '高雄'],
                    columns = ['one', 'two', 'three', 'four']
                   )
data

one  two  three  four
台北    0    1      2     3
台中    4    5      6     7
台南    8    9     10    11
高雄   12   13     14    15

In [44]:
data['one']

台北     0
台中     4
台南     8
高雄    12
Name: one, dtype: int64

In [45]:
data[['one','two']]

one  two
台北    0    1
台中    4    5
台南    8    9
高雄   12   13

In [47]:
data[0:2]

one  two  three  four
台北    0    1      2     3
台中    4    5      6     7

In [48]:
#dataFrame.iloc[]
#dataFrame.loc[]

data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index = ['台北','台中','台南', '高雄'],
                    columns = ['one', 'two', 'three', 'four']
                   )
data

one  two  three  four
台北    0    1      2     3
台中    4    5      6     7
台南    8    9     10    11
高雄   12   13     14    15

In [50]:
data.loc[['台北','台中'],['two','three']]

two  three
台北    1      2
台中    5      6

In [51]:
data.iloc[[0,1],[1,2]]

two  three
台北    1      2
台中    5      6

In [53]:
data.loc[['台北','台中']]

one  two  three  four
台北    0    1      2     3
台中    4    5      6     7